EventTicket_Text_OldSeaMapTooFar:
	.string "怎么了，年轻人?\p"
	.string "哦，是你应该有一张破旧的旧地图吗?\p"
	.string "让我看看.\n"
	.string "… … … … … …\p"
	.string "孩子, 这地方真的很远.\n"
	.string "我恐怕帮不了你…$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "哈奇: 等一下!\p"
	.string "拒绝我的恩人\n"
	.string "是什么意思?$"

EventTicket_Text_BrineyLetsSail:
	.string "{PLAYER}{KUN}, 我真的很抱歉.\p"
	.string "你来找我寻求帮助,\n"
	.string "我们差点就拒绝了你.\p"
	.string "嗯，让我来纠正这件事.\p"
	.string "我们当然会立即启航!\p"
	.string "让我们一起根据\n"
	.string "这张旧海图找到这个岛屿!$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "“是你带来了\n"
	.string "那张奇怪的船票吗?\p"
	.string "你试图去的是一个\n"
	.string "非常非常遥远的岛屿.\p"
	.string "没有人知道那里有什么在等待…\p"
	.string "光是想想就让我这个\n"
	.string "水手热血沸腾!\p"
	.string "上船吧，年轻人!$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "哈奇船长可能非常令人恼火地变化无常\n"
	.string "……\p"
	.string "你想回到水静市吗?$"

BirthIsland_Harbor_Text_SailorReturn:
	.string "这个岛屿的形状真奇怪，不是吗?\n"
	.string "你想回到水静市吗?$"

EventTicket_Text_OddTicketsWhereTo:
	.string "是你带来了那些\n"
	.string "奇怪的船票吗?\p"
	.string "… … …嗯.\p"
	.string "这些票会带你去\n"
	.string "非常非常遥远的岛屿.\p"
	.string "没人知道那里有什么,\n"
	.string "或者那里会发生什么.\p"
	.string "作为一个\n"
	.string "航海家!\p"
	.string "这个想法让我的血液沸腾!\n"
	.string "上船吧，年轻人！我们首先应该航行去哪里?$"

NavelRock_Harbor_Text_SailorReturn:
	.string "你……你听到了吗?\n"
	.string "从那里深处传来的低沉的咆哮声.\p"
	.string "你确定这里安全吗?\n"
	.string "你认为我们应该离开吗?$"

FarawayIsland_Entrance_Text_Sign:
	.string "文字已经褪色\n"
	.string "似乎是很久以前写的…\p"
	.string "“…月，6日\n"
	.string "如果有人……再次踏足这里…\l"
	.string "希望他/她是一个心地善良的人…\l"
	.string "…带着这个希望，我离开了…”$"

FarawayIsland_Interior_Text_Mew:
	.string "妙呜...$"
