Questionnaire_Text_FillOut::
	.string "这里有一个问卷调查\n"
	.string "您想要填写它吗?$"

Questionnaire_Text_ThankYou::
	.string "感谢您抽出时间填写我们的问卷\n"
	.string "您的反馈将用于将来的参考.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "哦，你好!\n"
	.string "你知道那些词汇吗?\p"
	.string "那意味着\n"
	.string "你一定知道神秘礼物.\p"
	.string "从现在开始\n"
	.string "你应该会收到神秘礼物!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "一旦你保存了游戏\n"
	.string "你就可以访问神秘礼物.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "哦，你好!\n"
	.string "你知道那些词汇吗?\p"
	.string "那意味着\n"
	.string "你一定知道神秘事件.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "一旦你保存了游戏\n"
	.string "你就可以访问神秘事件.$"

MysteryGift_Text_TheresATicketForYou::
	.string "T感谢您使用\n"
	.string "神秘事件系统.\p"
	.string "您一定是{PLAYER}吧.\n"
	.string "这里有一张票是给您的.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "它看起来是在\n"
	.string "水静市港口使用的.\p"
	.string "为什么不试试看\n"
	.string "了解它究竟是关于什么的?$"
