SecretBase_Text_Trainer0Intro:
	.string "你已经创建了一个秘密基地了吗?\p"
	.string "我到处走来走去\n"
	.string "最后选择了这个地方.\p"
	.string "既然你已经在这里了\n"
	.string "你想不想来一场对战?$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "好的!\n"
	.string "我们上吧!$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "嗯?\n"
	.string "哦，你现在不能对战…$"

SecretBase_Text_Trainer0Defeated::
	.string "哇啊！你太强了!\n"
	.string "关于我输了这件事……请保密!$"

SecretBase_Text_Trainer0PostBattle:
	.string "你觉得我的秘密基地怎么样?\n"
	.string "明天再来拜访我吧.$"

SecretBase_Text_Trainer0PreChampion:
	.string "你已经创建了一个秘密基地了吗?\p"
	.string "我到处走来走去,\n"
	.string "最后选择了这个地方.\p"
	.string "随意在这里休息吧!$"

SecretBase_Text_Trainer5Intro:
	.string "有很多可以创建秘密基地的地方\n"
	.string "但我最喜欢这个地方.\p"
	.string "你不认为这里很棒吗?\p"
	.string "哦\p"
	.string "你想不想来一场对战?$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "好，那就来吧!$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "哦…\n"
	.string "你现在不能对战, 好吧.$"

SecretBase_Text_Trainer5Defeated::
	.string "嗯…我们输了…\n"
	.string "但是不要告诉任何人!\l"
	.string "这是一个需要保守的秘密!$"

SecretBase_Text_Trainer5PostBattle:
	.string "如果你再次来到这个区域,\n"
	.string "我希望你能来拜访我.$"

SecretBase_Text_Trainer5PreChampion:
	.string "有很多可以创建秘密基地的地方\p"
	.string "但我最喜欢这个地方.\n"
	.string "你不认为这里很不错吗?$"

SecretBase_Text_Trainer1Intro:
	.string "这是一个热门地点.\n"
	.string "总是被占用的.\p"
	.string "哦！你是不是也在考虑\n"
	.string "占据这个地方?\p"
	.string "我告诉你，如果你能打败我\n"
	.string "你就可以拥有这个地方.$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "好!\n"
	.string "我将保卫我的秘密基地!$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "嗯?是这样吗?\n"
	.string "你对这个地方不感兴趣吗?$"

SecretBase_Text_Trainer1Defeated::
	.string "我无法再继续战斗了!\n"
	.string "我投降!$"

SecretBase_Text_Trainer1PostBattle:
	.string "好的,等我有一天搬走,\n"
	.string "这个地方就会是你的!$"

SecretBase_Text_Trainer1PreChampion:
	.string "这是一个热门地点.\n"
	.string "总是被占用的.\p"
	.string "我等了很久才等到它空出来.\n"
	.string "我终于能够使用它了!$"

SecretBase_Text_Trainer6Intro:
	.string "欢迎来到我的宝可梦实验室.\p"
	.string "我在这里\n"
	.string "秘密进行对战研究.\p"
	.string "你想看看我有多强吗?$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "我会全力以赴!$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "哦.\n"
	.string "那下次吧!$"

SecretBase_Text_Trainer6Defeated::
	.string "嗯…我还有很多要学习的地方.\n"
	.string "我得再研究一下.$"

SecretBase_Text_Trainer6PostBattle:
	.string "谢谢你和我对战.\n"
	.string "请明天再来.$"

SecretBase_Text_Trainer6PreChampion:
	.string "欢迎来到我的宝可梦实验室.\p"
	.string "我在这里\n"
	.string "秘密进行对战研究.$"

SecretBase_Text_Trainer2Intro:
	.string "大房子很好，但我更喜欢\n"
	.string "这样的地方.\p"
	.string "我喜欢这里因为各种各样的人\n"
	.string "都会来拜访我.\p"
	.string "那么，你想不想来一场对战?$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "就这样!$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "当你准备好了，就喊我一声!$"

SecretBase_Text_Trainer2Defeated::
	.string "啊！我输了!\n"
	.string "但对战仍然很有趣!$"

SecretBase_Text_Trainer2PostBattle:
	.string "嗯，不管怎样，我应该去买些\n"
	.string "装饰品和家具.\p"
	.string "我希望我的秘密基地是一个\n"
	.string "其他人也能享受的地方.$"

SecretBase_Text_Trainer2PreChampion:
	.string "大房子很好，但我更喜欢\n"
	.string "这样的地方.\p"
	.string "我喜欢这里因为各种各样的人\n"
	.string "都会来拜访我.$"

SecretBase_Text_Trainer7Intro:
	.string "我非常喜欢\n"
	.string "购物买装饰品和家具.\p"
	.string "我也非常喜欢\n"
	.string "培养宝可梦.\p"
	.string "如果你愿意的话,\n"
	.string "能和我对战吗?$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "谢谢你.\n"
	.string "我们开始吧?$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "哦.\n"
	.string "真令人失望…$"

SecretBase_Text_Trainer7Defeated::
	.string "我认输…$"

SecretBase_Text_Trainer7PostBattle:
	.string "这真是一场愉快的对战!\n"
	.string "我现在应该去享受购物了.$"

SecretBase_Text_Trainer7PreChampion:
	.string "我非常喜欢购物买\n"
	.string "装饰品和家具.\p"
	.string "我也非常喜欢\n"
	.string "培养宝可梦.$"

SecretBase_Text_Trainer3Intro:
	.string "有些人在难以找到的地方\n"
	.string "创建他们的秘密基地.\l"
	.string "他们是不是只想低调?\p"
	.string "但既然你找到了我\n"
	.string "我们来一场对战怎么样?$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "我不会那么容易就被打败的!$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "哦…你是不是因为寻找这个地方\n"
	.string "而感到累了?$"

SecretBase_Text_Trainer3Defeated::
	.string "我被打败了…$"

SecretBase_Text_Trainer3PostBattle:
	.string "你的秘密基地在哪里?\n"
	.string "我也应该去你那里拜访一下.$"

SecretBase_Text_Trainer3PreChampion:
	.string "有些人在难以找到的地方\n"
	.string "创建他们的秘密基地.\l"
	.string "他们是不是只想低调?$"

SecretBase_Text_Trainer8Intro:
	.string "人们告诉我\n"
	.string "你可以通过几种方式获得装饰品.\p"
	.string "我们应该进行一场比赛\n"
	.string "看看谁能获得更好的装饰品和家具!\p"
	.string "与此同时，想不想对战?$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "这是我的秘密基地.\n"
	.string "我不能输!$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "我随时都可以和你对战.$"

SecretBase_Text_Trainer8Defeated::
	.string "啊?\n"
	.string "我刚刚输了吗?$"

SecretBase_Text_Trainer8PostBattle:
	.string "在收集装饰品方面我不会输.\n"
	.string "再来拜访吧!$"

SecretBase_Text_Trainer8PreChampion:
	.string "人们告诉我\n"
	.string "你可以通过几种方式获得装饰品.\p"
	.string "我们应该进行一场比赛\n"
	.string "看看谁能获得更好的装饰品和家具!$"

SecretBase_Text_Trainer4Intro:
	.string "我找到了一个我喜欢的地方\n"
	.string "并用我最喜欢的装饰品装饰了它.\p"
	.string "我培养我最喜欢的宝可梦\n"
	.string "并与它一起变得更强.\p"
	.string "这就是我所做的.\n"
	.string "想和我对战吗?$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "让我看看你的实力!$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "我想有时候\n"
	.string "你可能并不感兴趣.$"

SecretBase_Text_Trainer4Defeated::
	.string "我现在完全知道你的实力了.$"

SecretBase_Text_Trainer4PostBattle:
	.string "我们都可以变得更强.\n"
	.string "让我们继续努力!$"

SecretBase_Text_Trainer4PreChampion:
	.string "我找到了一个我喜欢的地方\n"
	.string "并用我最喜欢的装饰品装饰了它.\p"
	.string "我培养我最喜欢的宝可梦\n"
	.string "并与它一起变得更强.\p"
	.string "每一天都是美好的一天.$"

SecretBase_Text_Trainer9Intro:
	.string "你可以通过人们拥有的装饰品种类\n"
	.string "以及他们展示的方式\l"
	.string "了解很多关于他们的品味和感觉\l"
	.string "你觉得我的品味如何.\p"
	.string "你是不是无言以对?\n"
	.string "想不想见识一下?\p"
	.string "我在对战中的品味?$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "我不会留手的!$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "我随时都乐意展示\n"
	.string "我的战斗风格.$"

SecretBase_Text_Trainer9Defeated::
	.string "你的才能无与伦比!\n"
	.string "你的力量似乎无穷无尽…$"

SecretBase_Text_Trainer9PostBattle:
	.string "你觉得我的战斗风格怎么样?\n"
	.string "我会继续磨练它!$"

SecretBase_Text_Trainer9PreChampion:
	.string "你可以通过\n"
	.string "人们拥有的装饰品种类\l"
	.string "以及他们展示的方式\l"
	.string "了解很多关于他们的品味和感觉.\p"
	.string "你觉得我的品味如何?\n"
	.string "你是不是无言以对?$"
